version: "3"

services:
  nomad-agent:
    build:
      context: ./nomad
      args:
        # latest version is found here: https://github.com/hashicorp/nomad/releases
        NOMAD_VERSION: 0.12.5
        http_proxy: null  # use host env
        https_proxy: null # use host env
    command: [ "agent", "-dev", "-bind=0.0.0.0" ]
    environment:
      http_proxy: null  # use host env
      https_proxy: null # use host env
    privileged: true
    tmpfs:
      - /tmp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/home/nomad
    ports:
        - 127.0.0.1:4646:4646 # HTTP
        - 127.0.0.1:4647:4647 # RPC
