version: "3"

services:
  nomad-agent:
    build:
      context: ./nomad
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    command: [ "agent", "-dev", "-bind=0.0.0.0" ]
    environment:
      - http_proxy
      - https_proxy
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
    ports:
        - 127.0.0.1:4646:4646 # HTTP
        - 127.0.0.1:4647:4647 # RPC
